# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: hand
  joint_model_group_pose: close
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    - panda_finger_joint1
    #- panda_finger_joint2
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains:
    shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_finger_joint1
    #- panda_finger_joint2
  gains:
    panda_finger_joint1: { p: 5, d: 3.0, i: 0, i_clamp: 1 }
    #panda_finger_joint2: { p: 5, d: 1.0, i: 0, i_clamp: 1 }

  state_publish_rate: 25

controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - panda_finger_joint1
      #- panda_finger_joint2
    constraints:
      #stopped_velocity_tolerance: 0
      goal_time: 0.1
      panda_finger_joint1:
        goal: 0.001